"use client"

import { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription, CardFooter } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { 
  History, 
  Search, 
  ShieldCheck, 
  Database, 
  ExternalLink, 
  Link as LinkIcon, 
  AlertTriangle, 
  BrainCircuit, 
  Sparkles, 
  Fingerprint,
  ChevronRight,
  ShieldAlert
} from 'lucide-react';
import { mockLogs } from '@/lib/mock-data';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { analyzeAuditLedger, ForensicAnalysisOutput } from '@/ai/flows/forensic-log-analysis';

export default function LogsPage() {
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [analysis, setAnalysis] = useState<ForensicAnalysisOutput | null>(null);

  const handleAIAnalysis = async () => {
    setIsAnalyzing(true);
    try {
      const result = await analyzeAuditLedger({ logs: mockLogs });
      setAnalysis(result);
    } catch (error) {
      console.error("Forensic analysis error:", error);
    } finally {
      setIsAnalyzing(false);
    }
  };

  return (
    <div className="space-y-8 animate-in slide-in-from-right-4 duration-500">
      <div className="flex justify-between items-end">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">Immutable Audit Ledger</h1>
          <p className="text-muted-foreground">Blockchain-verified forensic security evidence</p>
        </div>
        <div className="flex gap-4">
          <Button 
            onClick={handleAIAnalysis}
            disabled={isAnalyzing}
            className="bg-accent hover:bg-accent/90 text-accent-foreground font-bold flex items-center gap-2 px-6"
          >
            {isAnalyzing ? (
              <BrainCircuit className="w-4 h-4 animate-spin" />
            ) : (
              <Sparkles className="w-4 h-4" />
            )}
            {isAnalyzing ? "Analyzing Ledger..." : "AI Forensic Deep Scan"}
          </Button>
          <div className="bg-accent/10 border border-accent/20 px-4 py-2 rounded-lg flex items-center gap-2">
            <LinkIcon className="w-4 h-4 text-accent" />
            <span className="text-sm font-mono text-accent">Chain Height: 1,842,910</span>
          </div>
        </div>
      </div>

      {analysis && (
        <Card className="border-accent/30 bg-accent/5 animate-in zoom-in-95 duration-500 overflow-hidden relative">
          <div className="absolute top-0 right-0 p-4 opacity-10">
            <BrainCircuit className="w-24 h-24 text-accent" />
          </div>
          <CardHeader>
            <CardTitle className="text-accent flex items-center gap-2">
              <ShieldAlert className="w-5 h-5" />
              AI Forensic Analysis Report
            </CardTitle>
            <CardDescription className="text-accent/70">Forensic insights generated by the Cognitive Security Module</CardDescription>
          </CardHeader>
          <CardContent className="grid grid-cols-1 md:grid-cols-2 gap-8">
            <div className="space-y-4">
              <div>
                <h4 className="text-xs font-bold uppercase tracking-widest text-accent mb-2">Integrity Verification</h4>
                <p className="text-sm leading-relaxed text-muted-foreground bg-black/20 p-3 rounded-lg border border-accent/10">
                  {analysis.integrityReport}
                </p>
              </div>
              <div>
                <h4 className="text-xs font-bold uppercase tracking-widest text-accent mb-2">Conclusion</h4>
                <p className="text-sm font-medium italic text-foreground">
                  "{analysis.forensicConclusion}"
                </p>
              </div>
            </div>
            <div className="space-y-4">
              <div>
                <h4 className="text-xs font-bold uppercase tracking-widest text-accent mb-2">Anomalies Detected</h4>
                <div className="space-y-2">
                  {analysis.anomaliesDetected.map((anomaly, i) => (
                    <div key={i} className="flex items-start gap-2 text-sm text-muted-foreground">
                      <ChevronRight className="w-4 h-4 text-accent mt-0.5 shrink-0" />
                      <span>{anomaly}</span>
                    </div>
                  ))}
                </div>
              </div>
              <div>
                <h4 className="text-xs font-bold uppercase tracking-widest text-accent mb-2">Mitigation Strategy</h4>
                <div className="p-3 bg-primary/10 border border-primary/20 rounded-lg text-sm text-primary-foreground font-mono">
                  {analysis.suggestedMitigation}
                </div>
              </div>
            </div>
          </CardContent>
          <CardFooter className="bg-accent/10 py-2 border-t border-accent/20">
            <p className="text-[10px] font-mono text-accent/60 mx-auto uppercase tracking-tighter">
              Analysis timestamp: {new Date().toISOString()} // SIGNATURE: AI-FORENSIC-V4
            </p>
          </CardFooter>
        </Card>
      )}

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <Card className="border-border/50 bg-card/50">
          <CardHeader className="pb-2">
            <CardTitle className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Ledger Integrity</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="flex items-center gap-2 mb-1">
              <ShieldCheck className="w-5 h-5 text-primary" />
              <span className="text-xl font-bold">Verified Tamper-Proof</span>
            </div>
            <p className="text-xs text-muted-foreground">Cryptographic proofs consistent across 12 distributed nodes.</p>
          </CardContent>
        </Card>
        <Card className="border-border/50 bg-card/50">
          <CardHeader className="pb-2">
            <CardTitle className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Forensic Manager</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="flex items-center gap-2 mb-1">
              <Database className="w-5 h-5 text-accent" />
              <span className="text-xl font-bold">Snapshot: May 20, 2024</span>
            </div>
            <p className="text-xs text-muted-foreground">Forensic evidence preserved for incident #420-B.</p>
          </CardContent>
        </Card>
        <Card className="border-border/50 bg-card/50">
          <CardHeader className="pb-2">
            <CardTitle className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Active Threats Logs</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="flex items-center gap-2 mb-1">
              <AlertTriangle className="w-5 h-5 text-destructive" />
              <span className="text-xl font-bold">2 Anomalies Flagged</span>
            </div>
            <p className="text-xs text-muted-foreground">Requires administrator review of risk-adaptive actions.</p>
          </CardContent>
        </Card>
      </div>

      <Card className="border-border/50 bg-card/50 overflow-hidden">
        <CardHeader className="flex flex-row items-center justify-between border-b border-border/50 bg-muted/20">
          <div className="flex items-center gap-4">
            <div className="relative w-72">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
              <Input placeholder="Filter by hash, event, or status..." className="pl-10 h-10 bg-muted/30 border-border/50" />
            </div>
            <Badge variant="outline" className="border-primary/50 text-primary">Live Syncing...</Badge>
          </div>
          <div className="text-xs text-muted-foreground font-mono">
            PROTOCOL: BCT-LEGER-V2
          </div>
        </CardHeader>
        <CardContent className="p-0">
          <Table>
            <TableHeader className="bg-muted/30">
              <TableRow className="border-border/50">
                <TableHead>Timestamp</TableHead>
                <TableHead>Security Event</TableHead>
                <TableHead>System Status</TableHead>
                <TableHead>Risk Score</TableHead>
                <TableHead>Block Hash</TableHead>
                <TableHead className="text-right">Link</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {mockLogs.map((log) => (
                <TableRow key={log.id} className="border-border/50 hover:bg-muted/10 transition-colors group">
                  <TableCell className="text-muted-foreground font-mono text-xs">{log.timestamp}</TableCell>
                  <TableCell className="font-semibold">{log.event}</TableCell>
                  <TableCell>
                    <Badge 
                      variant={log.status === 'Mitigated' ? 'default' : log.status === 'Success' ? 'secondary' : 'outline'}
                      className={log.status === 'Encrypted' ? 'bg-accent/20 text-accent border-accent/20' : ''}
                    >
                      {log.status}
                    </Badge>
                  </TableCell>
                  <TableCell>
                    <div className="flex items-center gap-2">
                      <div className="w-16 h-1 bg-muted rounded-full overflow-hidden">
                        <div 
                          className={`h-full ${log.risk > 0.5 ? 'bg-destructive' : log.risk > 0.1 ? 'bg-primary' : 'bg-accent'}`} 
                          style={{ width: `${log.risk * 100}%` }}
                        />
                      </div>
                      <span className="text-xs font-mono">{(log.risk * 100).toFixed(0)}%</span>
                    </div>
                  </TableCell>
                  <TableCell className="text-muted-foreground font-mono text-[10px] tracking-widest">{log.blockHash}</TableCell>
                  <TableCell className="text-right">
                    <ExternalLink className="w-4 h-4 ml-auto text-muted-foreground opacity-0 group-hover:opacity-100 transition-opacity cursor-pointer hover:text-primary" />
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </CardContent>
      </Card>
    </div>
  );
}
